name: Build RXB Windows
on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64 -y
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix

      - name: Fix Missing Depends
        run: |
          git clone --depth 1 --branch v0.20.1 https://github.com temp_btc
          cp -R temp_btc/depends/. depends/
          rm -rf temp_btc

      - name: Build depends
        run: |
          cd depends
          make HOST=x86_64-w64-mingw32 -j$(nproc)

      - name: Build RXB Core
        run: |
          ./autogen.sh
          CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-tests --disable-bench --with-incompatible-bdb
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RXB-Core-Windows
          path: |
            src/rxbd.exe
            src/rxb-cli.exe
            src/qt/rxb-qt.exe
