name: Build RXB Windows (No GUI)
on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64 -y
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix

      - name: Fix Missing Depends
        run: |
          # Metodo Sparse-Checkout: scarica solo la cartella depends da Bitcoin v0.20.1
          git clone --filter=blob:none --no-checkout https://github.com btc_build
          cd btc_build
          git checkout v0.20.1 -- depends
          cd ..
          mkdir -p depends
          cp -rv btc_build/depends/* depends/
          rm -rf btc_build
          # Verifica che il Makefile sia al suo posto
          ls -la depends/Makefile

      - name: Build depends
        run: |
          cd depends
          # NO_QT=1 evita l'errore delle librerie grafiche che non ti servono per il mining
          make HOST=x86_64-w64-mingw32 -j$(nproc) NO_QT=1

      - name: Build RXB Core
        run: |
          ./autogen.sh
          # Configurazione ottimizzata per un nodo da mining (No GUI, No Tests)
          CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-tests --disable-bench --with-incompatible-bdb --without-gui
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RXB-Core-Windows-NoGUI
          path: |
            src/rxbd.exe
            src/rxb-cli.exe
